GET http://localhost:4000/user/1
Content-Type: application/json

### Create

POST http://localhost:4000/user/create
Content-Type: application/json

{
    "email": "jhon@doe.fr",
    "password": "test18",
    "firstname": "jhon",
    "lastname": "doe"
}

### Update

PUT http://localhost:4000/user/update/1
Content-Type: application/json

{
    "email": "test@doe.com",
    "password": "test123",
    "firstname": "jean",
    "lastname": "robert"
}

### Delete

DELETE http://localhost:4000/user/delete
Content-Type: application/json

{
    "id": 1
}

###

GET http://localhost:4000/api-docs