GET http://localhost:4000/user/3?apiKey={{$dotenv API_KEY}}

### Create

POST http://localhost:4000/user/create?apiKey={{$dotenv API_KEY}}
Content-Type: application/json

{
    "email": "doe@jhon.fr",
    "password": "test2",
    "firstname": "jhon2",
    "lastname": "doe2"
}

### Update

PUT http://localhost:4000/user/update/3?apiKey={{$dotenv API_KEY}}
Content-Type: application/json

{
    "email": "test@doe.com",
    "password": "test123",
    "firstname": "jean",
    "lastname": "robert"
}

### Delete

DELETE http://localhost:4000/user/delete?apiKey={{$dotenv API_KEY}}
Content-Type: application/json

{
    "id": 3
}